name: data_tables
description: ListView on Mobile and Stateless Data Tables on Tablets and Desktops.
version: 1.1.1-nullsafety.0
author: Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/data_tables
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
